### ISSUE TITLE
Backprop 3d pooling doesn't work

### ISSUE THREAD

**Issue by SSBomma** [pengsun/MexConv3D#1]
Hi Pengsun,

I was trying out the 3d convolution and pooling operations on some random data. The 3d convolution seems working fine but couldn't get 3d pooling backprop working.
Could you please check the following code and let me know the error? Single pooling block works well but when connected between convolution layers, during backpropagation, there is an issue with dimensions. In the following code the dimension don't match during backprop after the layer 6(pooling layer)
Also in matconvnet the pooling block for backpropagation takes vl_nnpool(X,pool,dzdy,stride...)
But 3d pooling takes only mex_maxpool3d(dzdy,ind,pool,stride...). and not X?
Please let me know if there is any error to be corrected in the code.
Thanks in advance!
Sushma
%%Code begins
X = gpuArray.rand(60,80,13,'single');   % random data
label = 1;
pool  = [2,2,2];          % 3D pooling window size
p_str = [2,2,1];           % 3D pooling stride 
c_str = [1,1,1];           % 3D conv stride

F1 = 0.01_(gpuArray.rand(7,7,3,1,100, 'single')); B1 = 0.01_(gpuArray.rand(1,100, 'single'));
F3 = 0.01_(gpuArray.rand(5,5,3,100,50,'single')); B3 = 0.01_(gpuArray.rand(1,50,'single'));
F5 = 0.01_(gpuArray.rand(5,5,3,50,50,'single')); B5 = 0.01_(gpuArray.rand(1,50,'single'));
F7 = 0.01_(gpuArray.rand(3,3,3,50,50,'single')); B7 = 0.01_(gpuArray.rand(1,50,'single'));
F8 = 0.01_(gpuArray.rand(1,4,2,50,50,'single')); B8 = 0.01_(gpuArray.rand(1,50,'single'));
F9 = 0.01_(gpuArray.rand(1,1,1,50,6,'single')); B9 = 0.01_(gpuArray.rand(1,6,'single'));

%% fprop
res.x1 = mex_conv3d(X,F1,B1,'stride',c_str);                       % 1
[res.x2, ind2] = mex_maxpool3d(res.x1,'pool',pool,'stride',p_str); % 2
res.x3 = mex_conv3d(res.x2,F3,B3,'stride',c_str);                  % 3
[res.x4, ind4] = mex_maxpool3d(res.x3,'pool',pool,'stride',p_str); % 4
res.x5 = mex_conv3d(res.x4,F5,B5,'stride',c_str);                  % 5
[res.x6, ind6] = mex_maxpool3d(res.x5,'pool',pool,'stride',p_str); % 6
res.x7 = mex_conv3d(res.x6,F7,B7,'stride',c_str);                  % 7
res.x8 = mex_conv3d(res.x7,F8,B8,'stride',c_str);                  % 8
res.x9 = mex_conv3d(res.x8,F9,B9,'stride',c_str);                  % 9
y = vl_nnsoftmaxloss(res.x9,label);                                    %10

%% bprop
one = gpuArray(single(1)) ;
res.dzdy = one;
res.dzdx8 = vl_nnsoftmaxloss(res.x9,label,res.dzdy);                                  %10
[res.dzdx7,res.dzdF9,res.dzdB9] = mex_conv3d(res.x8,F9,B9, res.dzdx8,'stride',c_str); % 9
[res.dzdx6,res.dzdF8,res.dzdB8] = mex_conv3d(res.x7,F8,B8, res.dzdx7,'stride',c_str); % 8
[res.dzdx5,res.dzdF7,res.dzdB7] = mex_conv3d(res.x6,F7,B7, res.dzdx6,'stride',c_str); % 7
res.dzdx4 = mex_maxpool3d(res.dzdx5,ind6,'pool',pool,'stride',p_str);                 % 6
[res.dzdx3,res.dzdF5,res.dzdB5] = mex_conv3d(res.x4,F5,B5, res.dzdx4,'stride',c_str); % 5
res.dzdx2 = mex_maxpool3d(res.dzdx3,ind4,'pool',pool,'stride',p_str);                 % 4
[res.dzdx2,res.dzdF3,res.dzdB3] = mex_conv3d(res.x2,F3,B3, res.dzdx2,'stride',c_str); % 3
res.dzdx1 = mex_maxpool3d(res.dzdx2,ind2,'pool',pool,'stride',p_str);                 % 2
[res.dzdx,res.dzdF1,res.dzdB1] = mex_conv3d(X,F1,B1, res.dzdx1,'stride',c_str);       % 1

**Comment by pengsun** [comment]
Hi Sushma,

I think the problem could lie in this line of code:

``` Matlab
y = vl_nnsoftmaxloss(res.x9,label); %10
```

For 3D ConvNet, everything should be a 5D array:
- for `x` data: size(1:3) accounts for the size of the cube (a volume or a video), size(4) for #channels, size(5) for #instances
- for `F` data: size(1:3) for cubic filter size, size(4) for #input channels, size(5) for #output channels

However, `vl_nnsoftmaxloss` essentially works on 4D array (2D ConvNet) so that size(4) of the input `x` data would be recognized as #instances, which causes the error (BTW you forgot to define `label` in the code you post here?). 

I guess a minor modification (reshaping, I mean) to the code would easily fix the problem (someone else has reported her successful modification to make the code work with vlfeat/matconvnet). Also, if you are actually working on 2D data and you just want the index for max pooling output, you could just reshape the the data before feeding them into `mex_maxpool3d` and you don't need `mex_conv3d` at all.

Hope this helps and let me know if this solves the problem!

Peng

**Comment by SSBomma** [comment]
Thanks for getting back Peng!

I have changed the vl_nnsoftmaxloss to handle 5D data before using it for my 3d data (videos for action recognition). And I want to extract the local motion by applying 3d convolution, 3d pooling. Sorry, I missed the label here. It is '1' here.
I still have not got it running.

**Comment by pengsun** [comment]
Hi, could you send the complete testing code to my gmail? I'd like to see if I can fix it.

**Comment by SSBomma** [comment]
Seems to work now after modifying the filter sizes.
Thanks for your help :)

**Comment by pengsun** [comment]
The old interface to `mex_conv3d` is actually problematic. A new interface has been provided since v0.2
